-- ==================================================================
-- ms_negara: 208 baris dari master_exim_reference (sheet ms_negara).
-- Idempotent (INSERT IGNORE).
-- ==================================================================
USE kkp_exim_platform;

INSERT IGNORE INTO ms_negara (kode_negara, nama_negara, kelompok_negara) VALUES
('AD', 'Andorra', 'Lainnya'),
('AE', 'UNITED ARAB EMIRATES', 'Timur Tengah'),
('AF', 'AFGHANISTAN', 'Timur Tengah'),
('AG', 'ANTIGUA AND BARBUDA', 'Lainnya'),
('AI', 'ANGUILLA', 'Lainnya'),
('AL', 'ALBANIA', 'Lainnya'),
('AM', 'ARMENIA', 'Eurasia'),
('AN', 'NETHERLANDS ANTILLES', 'Lainnya'),
('AO', 'ANGOLA', 'Lainnya'),
('AR', 'ARGENTINA', 'Lainnya'),
('AS', 'AMERICAN SAMOA', 'Lainnya'),
('AT', 'AUSTRIA', 'Uni Eropa'),
('AU', 'AUSTRALIA', 'Australia And New Zealand'),
('AW', 'ARUBA', 'Lainnya'),
('AZ', 'AZERBAIJAN', 'Lainnya'),
('BA', 'BOSNIA AND HERZEGOVINA', 'Lainnya'),
('BB', 'BARBADOS', 'Lainnya'),
('BD', 'BANGLADESH', 'Lainnya'),
('BE', 'BELGIUM', 'Uni Eropa'),
('BF', 'BURKINA FASO', 'Lainnya'),
('BG', 'BULGARIA', 'Uni Eropa'),
('BH', 'BAHRAIN', 'Timur Tengah'),
('BJ', 'BENIN', 'Lainnya'),
('BL', 'SAINT BARTHELEMY', 'Lainnya'),
('BM', 'BERMUDA', 'Lainnya'),
('BN', 'BRUNEI DARUSSALAM', 'Asean'),
('BO', 'BOLIVIA', 'Lainnya'),
('BR', 'BRAZIL', 'Lainnya'),
('BS', 'BAHAMAS', 'Lainnya'),
('BT', 'BHUTAN', 'Lainnya'),
('BY', 'BELARUS', 'Eurasia'),
('BZ', 'BELIZE', 'Lainnya'),
('CA', 'CANADA', 'Canada'),
('CD', 'DEMOCRATIC REP. OF THE CONGO', 'Lainnya'),
('CF', 'CENTRAL AFRICAN REPUBLIC', 'Lainnya'),
('CG', 'CONGO', 'Lainnya'),
('CH', 'SWITZERLAND', 'EFTA'),
('CI', 'COTE D''IVOIRE', 'Lainnya'),
('CK', 'COOK ISLANDS', 'Lainnya'),
('CL', 'CHILE', 'Lainnya'),
('CM', 'CAMEROON', 'Lainnya'),
('CN', 'CHINA', 'China'),
('CO', 'COLOMBIA', 'Lainnya'),
('CR', 'COSTA RICA', 'Lainnya'),
('CU', 'CUBA', 'Lainnya'),
('CV', 'CAPE VERDE', 'Lainnya'),
('CW', 'CURACAO', 'Lainnya'),
('CX', 'CHRISTMAS ISLANDS', 'Lainnya'),
('CY', 'CYPRUS', 'Uni Eropa'),
('CZ', 'CZECH REPUBLIC', 'Uni Eropa'),
('DE', 'GERMANY, FED. REP. OF', 'Uni Eropa'),
('DJ', 'DJIBOUTI', 'Lainnya'),
('DK', 'DENMARK', 'Uni Eropa'),
('DM', 'DOMINICA', 'Lainnya'),
('DO', 'DOMINICAN REPUBLIC', 'Lainnya'),
('DZ', 'ALGERIA', 'Lainnya'),
('EC', 'ECUADOR', 'Lainnya'),
('EE', 'ESTONIA', 'Uni Eropa'),
('EG', 'EGYPT', 'Timur Tengah'),
('ES', 'SPAIN', 'Uni Eropa'),
('ET', 'ETHIOPIA', 'Lainnya'),
('FI', 'FINLAND', 'Uni Eropa'),
('FJ', 'FIJI', 'Lainnya'),
('FK', 'Falkland Islands (Malvinas)', 'Lainnya'),
('FM', 'MICRONESIA, FED. STATES OF', 'Lainnya'),
('FO', 'FAROE ISLANDS', 'Lainnya'),
('FR', 'FRANCE', 'Uni Eropa'),
('GA', 'GABON', 'Lainnya'),
('GB', 'UNITED KINGDOM', 'United Kingdom'),
('GD', 'GRENADA', 'Lainnya'),
('GE', 'GEORGIA', 'Lainnya'),
('GG', 'GUERNSEY', 'Lainnya'),
('GH', 'GHANA', 'Lainnya'),
('GL', 'GREENLAND', 'Lainnya'),
('GM', 'GAMBIA', 'Lainnya'),
('GN', 'GUINEA', 'Lainnya'),
('GP', 'GUADELOUPE', 'Lainnya'),
('GQ', 'EQUATORIAL GUINEA', 'Lainnya'),
('GR', 'GREECE', 'Uni Eropa'),
('GT', 'GUATEMALA', 'Lainnya'),
('GU', 'GUAM', 'Lainnya'),
('GW', 'GUINEA BISSAU', 'Lainnya'),
('GY', 'GUYANA', 'Lainnya'),
('HK', 'HONG KONG', 'Hong Kong'),
('HN', 'HONDURAS', 'Lainnya'),
('HR', 'CROATIA', 'Uni Eropa'),
('HT', 'HAITI', 'Lainnya'),
('HU', 'HUNGARY', 'Uni Eropa'),
('ID', 'INDONESIA', 'Indonesia'),
('IE', 'IRELAND', 'Uni Eropa'),
('IL', 'ISRAEL', 'Timur Tengah'),
('IN', 'INDIA', 'Lainnya'),
('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'Lainnya'),
('IQ', 'IRAQ', 'Timur Tengah'),
('IR', 'IRAN (ISLAMIC REPUBLIC OF)', 'Timur Tengah'),
('IS', 'ICELAND', 'EFTA'),
('IT', 'ITALY', 'Uni Eropa'),
('JE', 'JERSEY', 'Lainnya'),
('JM', 'JAMAICA', 'Lainnya'),
('JO', 'JORDAN', 'Timur Tengah'),
('JP', 'JAPAN', 'Japan'),
('KE', 'KENYA', 'Lainnya'),
('KG', 'KYRGYZSTAN', 'Eurasia'),
('KH', 'CAMBODIA', 'Asean'),
('KI', 'KIRIBATI', 'Lainnya'),
('KM', 'COMOROS', 'Lainnya'),
('KP', 'KOREA, DEM. PEOPLE''S REP.', 'Lainnya'),
('KR', 'KOREA, REPUBLIC OF', 'Korea Selatan'),
('KW', 'KUWAIT', 'Timur Tengah'),
('KZ', 'KAZAKHSTAN', 'Eurasia'),
('LA', 'LAO PEOPLE''S DEM. REP.', 'Asean'),
('LB', 'LEBANON', 'Timur Tengah'),
('LK', 'SRI LANKA', 'Lainnya'),
('LR', 'LIBERIA', 'Lainnya'),
('LT', 'LITHUANIA', 'Uni Eropa'),
('LU', 'LUXEMBOURG', 'Uni Eropa'),
('LV', 'LATVIA', 'Uni Eropa'),
('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Lainnya'),
('MA', 'MOROCCO', 'Lainnya'),
('MC', 'MONACO', 'Lainnya'),
('MD', 'MOLDOVA, REPUBLIC OF', 'Lainnya'),
('ME', 'MONTENEGRO', 'Lainnya'),
('MG', 'MADAGASCAR', 'Lainnya'),
('MK', 'REP. OF MACEDONIA', 'Lainnya'),
('ML', 'MALI', 'Lainnya'),
('MM', 'MYANMAR', 'Asean'),
('MO', 'MACAU', 'Lainnya'),
('MP', 'NORTHERN MARIANA ISLANDS', 'Lainnya'),
('MQ', 'MARTINIQUE', 'Lainnya'),
('MR', 'MAURITANIA', 'Lainnya'),
('MT', 'MALTA', 'Uni Eropa'),
('MU', 'MAURITIUS', 'Lainnya'),
('MV', 'MALDIVES', 'Lainnya'),
('MW', 'MALAWI', 'Lainnya'),
('MX', 'MEXICO', 'Lainnya'),
('MY', 'MALAYSIA', 'Asean'),
('MZ', 'MOZAMBIQUE', 'Lainnya'),
('NA', 'NAMIBIA', 'Lainnya'),
('NC', 'NEW CALEDONIA', 'Lainnya'),
('NE', 'NIGER', 'Lainnya'),
('NG', 'NIGERIA', 'Lainnya'),
('NI', 'NICARAGUA', 'Lainnya'),
('NL', 'NETHERLANDS', 'Uni Eropa'),
('NO', 'NORWAY', 'EFTA'),
('NP', 'NEPAL', 'Lainnya'),
('NR', 'NAURU', 'Lainnya'),
('NZ', 'NEW ZEALAND', 'Australia And New Zealand'),
('OM', 'OMAN', 'Timur Tengah'),
('PA', 'PANAMA', 'Lainnya'),
('PE', 'PERU', 'Lainnya'),
('PF', 'FRENCH POLYNESIA', 'Lainnya'),
('PG', 'PAPUA NEW GUINEA', 'Lainnya'),
('PH', 'PHILIPPINES', 'Asean'),
('PK', 'PAKISTAN', 'Lainnya'),
('PL', 'POLAND', 'Uni Eropa'),
('PR', 'PUERTO RICO', 'Lainnya'),
('PS', 'PALESTINA', 'Timur Tengah'),
('PT', 'PORTUGAL', 'Uni Eropa'),
('PY', 'PARAGUAY', 'Lainnya'),
('QA', 'QATAR', 'Timur Tengah'),
('RE', 'REUNION', 'Lainnya'),
('RO', 'ROMANIA', 'Uni Eropa'),
('RS', 'SERBIA', 'Lainnya'),
('RU', 'RUSSIA FEDERATION', 'Rusia'),
('RW', 'RWANDA', 'Lainnya'),
('SA', 'SAUDI ARABIA', 'Timur Tengah'),
('SB', 'SOLOMON ISLANDS', 'Lainnya'),
('SC', 'SEYCHELLES', 'Lainnya'),
('SD', 'SUDAN', 'Lainnya'),
('SE', 'SWEDEN', 'Uni Eropa'),
('SG', 'SINGAPORE', 'Asean'),
('SH', 'SAINT HELENA', 'Lainnya'),
('SI', 'SLOVENIA', 'Uni Eropa'),
('SK', 'SLOVAKIA', 'Uni Eropa'),
('SL', 'SIERRA LEONE', 'Lainnya'),
('SM', 'SAN MARINO', 'Lainnya'),
('SN', 'SENEGAL', 'Lainnya'),
('SO', 'SOMALIA', 'Lainnya'),
('SR', 'SURINAME', 'Lainnya'),
('SV', 'EL SALVADOR', 'Lainnya'),
('SX', 'SINT MAARTEN (DUTCH PART)', 'Lainnya'),
('SY', 'SYRIA ARAB REPUBLIC', 'Timur Tengah'),
('TC', 'TURKS AND CAICOS ISLANDS', 'Lainnya'),
('TG', 'TOGO', 'Lainnya'),
('TH', 'THAILAND', 'Asean'),
('TL', 'EAST TIMOR', 'Lainnya'),
('TN', 'TUNISIA', 'Lainnya'),
('TO', 'TONGA', 'Lainnya'),
('TR', 'TURKEY', 'Timur Tengah'),
('TT', 'TRINIDAD AND TOBAGO', 'Lainnya'),
('TW', 'TAIWAN', 'Taiwan'),
('TZ', 'TANZANIA, UNITED REP. OF', 'Lainnya'),
('UA', 'UKRAINE', 'Lainnya'),
('UG', 'UGANDA', 'Lainnya'),
('US', 'UNITED STATES', 'United States'),
('UY', 'URUGUAY', 'Lainnya'),
('UZ', 'UZBEKISTAN', 'Lainnya'),
('VE', 'VENEZUELA', 'Lainnya'),
('VG', 'VIRGIN ISLANDS (BRITISH)', 'Lainnya'),
('VI', 'U.S. VIRGIN ISLANDS', 'Lainnya'),
('VN', 'VIET NAM', 'Asean'),
('VU', 'VANUATU', 'Lainnya'),
('WF', 'WALLIS AND FUTUNA ISLANDS', 'Lainnya'),
('WS', 'SAMOA', 'Lainnya'),
('YE', 'YEMEN', 'Timur Tengah'),
('YT', 'MAYOTTE', 'Lainnya'),
('ZA', 'SOUTH AFRICA', 'Lainnya'),
('ZM', 'ZAMBIA', 'Lainnya');
