-- ==================================================================
-- ms_komoditas: kamus 900 nilai klasifikasi
--   - master_exim_reference (kelompok_komoditas, prioritas_*, jenis_produk,
--     bentuk_produk_id/en, jenis_pengolahan, kategori_tuna, asal_bahan_baku)
--   - raw_exim_ekspor_202606 (komoditas_1/2-2017, komoditas_4-2024, komoditas_5-2026,
--     bentuk_1/3-2026/5, jenis, jenis_2-2026). Nilai '0' (tidak terklasifikasi) dilewati.
-- Idempotent (INSERT IGNORE).
-- ==================================================================
USE kkp_exim_platform;

INSERT IGNORE INTO ms_komoditas (nomenklatur, versi, nama, nama_en, sumber) VALUES
('komoditas', 'kelompok_komoditas', 'Mamalia Laut', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_ekspor_utama', 'Komoditas Lainnya', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_impor_utama', 'Komoditas Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Mamalia Laut', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Hidup', 'Live', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Penanganan Hidup', NULL, 'master_exim_reference'),
('tuna', 'kategori_tuna', 'Bukan TTC', NULL, 'master_exim_reference'),
('asalbahanbaku', 'asal_bahan_baku', 'Perikanan Tangkap', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Anjing Laut Singa', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Binatang Melata', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Reptil', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hewan Subpos 010611', NULL, 'master_exim_reference'),
('asalbahanbaku', 'asal_bahan_baku', 'Perikanan Budidaya', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Segar, Dingin Atau Beku', 'Fresh, Chilled Or Frozen', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pembekuan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Jeroan Ikan (Dapat Dimakan)', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Paha Kodok', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Katak', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Diasinkan Atau Dalam Air Garam, Dikeringkan, Diasapi', 'Salted Or In Brine, Dried, Smoked', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pengeringan/Penggaraman', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Ikan Hias', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_impor_utama', 'Ikan Konsumsi & Olahan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Hias Air Tawar', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Ikan Hias Air Tawar', 'Freshwater Ornamental Fish', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Koi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Mas', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Cupang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Arwana', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Hias', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Ikan Hias Air Laut', 'Marine Ornamental Fish', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Salmon-Trout', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Trout', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Sidat', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Belut', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Karper', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pembenihan Benih Cyprinus', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Benih Cyprinus Spp', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Cyprinus Spp Carassius', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pembenihan Benih Catla', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lele', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Tuna-Cakalang-Tongkol', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_ekspor_utama', 'Tuna-Cakalang-Tongkol', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Sirip Biru Atlantik dan Pasifik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Sirip Biru Selatan', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Ikan Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kerapu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Benih Ikan', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bandeng', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bandeng', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Kerapu', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Tilapia', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tilapia', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Hidup-Segar-Dingin', 'Live-Fresh-Chilled', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Laut N.e.c Pos', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Air Tawar Laut', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Segar-Dingin', 'Fresh Or Chilled', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Penanganan Segar/Dingin', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Salmon', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Halibut', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Halibut', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Plaice', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Plaice', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Sole', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sole', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Turbot', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Turbot', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Ikan Pipih Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pipih Halibut Plaice', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Albakora', NULL, 'master_exim_reference'),
('tuna', 'kategori_tuna', 'Tuna', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Sirip Kuning', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Cakalang', NULL, 'master_exim_reference'),
('tuna', 'kategori_tuna', 'Cakalang-Tongkol', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Mata Besar', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Lainnya', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Herring', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Haring', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Teri', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Teri', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Sarden-Sardinella', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sarden / Lemuru', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Makarel', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makarel', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Cobia', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kobia', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Todak', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Pedang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bonito / Makarel / Sarden', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Cod', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kod', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Haddock', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Haddock', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Coalfish', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Batu Bara', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Hake', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hake', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Alaska Pollack', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Alaska Pollack', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Blue Whitings', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Putih Biru', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bregmacerotidae', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Catfish', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Patin', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Gabus Dan Nile Perch', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Snakehead / Gabus', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Dogfish Dan Hiu Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Dogfish Hiu', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Pari Dan Skates', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sepat', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Tootfish', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Gigi Patagonian Toothfish', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Seabass', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kakap Putih', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Seabream', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kakap', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Longfin Mojarra', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Mojarra Sirip Panjang', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bluntnose Lizardfish', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kadal Berhidung Tumpul', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Layur, Gulama, Reeve''S Croakers, Bigeye Croakers', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Layur', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Indian Threadfins', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Threadfins India', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Scad Torpedo, Spotted Sicklefish, Barracuda Besar', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Torpedo Scads Sabit', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bawal', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bawal Hitam', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Kakap Merah', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kakap Merah', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Laut Lainnya', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Swamp barb', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Duri Rawa', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Silver Grunts', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Geram Perak', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Hilsa Shad', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hilsa Shad', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Hati-Telur Ikan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hati, Telur & Sisik Ikan', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Sirip Hiu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip Hiu', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bagian Ikan Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kepala, Ekor & Rahang Ikan', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Mentah Beku', 'Frozen Raw', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Gabus', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sol', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Utuh Beku', 'Frozen Whole', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Sirip Biru Atlantik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Sirip Biru Pasifik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Ekor Panjang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bawal', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pari Pari', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip Benang India', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tongkol', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kepala Ekor Isi', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Fillet', 'Fillets', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Nile Perch', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Nila', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Fillet Ikan', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Daging Lainnya', 'Other Meat', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Yang Dari Keluarga', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Yang Dari Gigi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Yang Dari Dogfish', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Dari Pari Pari', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Daging Ikan Olahan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tuna Olahan', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Lemadang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lemadang / Mahi-mahi', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Fillet Beku', 'Frozen Fillet', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Yang Dibekukan Dari', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Surimi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Surimi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Dari Kode Hs', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hati Telur Susu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hati, Telur & Milt Ikan Air Tawar', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Diasapi', 'Smoked', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pengasapan', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Dikeringkan', 'Dried', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kembung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bonito / Sarden', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Asin / Direndam Air Garam', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'diasinkan', 'Salted', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Diasinkan', 'Salted', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ikan Asin Kering', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip Hiu Air', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Air Garam Dari', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Bagian Ikan Yang Dapat Dimakan', 'Edible Fish Offal', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip/Ekor/Kepala Ikan Garam', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip Yang Direndam', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip Ikan Asin/Air Garam', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Lobster', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lobster', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Rajungan-Kepiting', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_ekspor_utama', 'Rajungan-Kepiting', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kepiting Bakau', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Diasapi Beku', 'Smoked-Frozen', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kepiting Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Rajungan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kepiting Subtropis', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Udang', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_ekspor_utama', 'Udang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Udang Subtropis', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Udang Windu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Udang Vaname', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Udang Galah', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Udang Lainnya', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Tepung Ikan-Pellet-Makanan Ikan', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_impor_utama', 'Tepung/Pakan Ikan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Krustasea Lainnya', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Layak Untuk Konsumsi Manusia', 'Fit For Human Consumption', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Olahan Ikan Lainnya', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Dalam Kemasan Kedap Udara', 'Smoked', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Tidak Dalam Kemasan Kedap Udara', 'Smoked', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kepiting Olahan', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Olahan Lainnya', 'Others', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pengalengan', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Kekerangan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tiram', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kerang', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Cumi-Sotong-Gurita', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_ekspor_utama', 'Cumi-Sotong-Gurita', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Cumi-Sotong', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Diolah-Diawetkan', 'Prepared-Preserved', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Gurita', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Siput Siput Laut', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Abalon', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Keong Stromboid', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Keong Stromboid Air', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Moluska Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Moluska (Dengan/Tanpa Cangkang)', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Teripang', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bulu Babi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bulu Babi', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Ubur-Ubur', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ubur-ubur', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Invertebrata Air Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Invertebrata Air Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makanan Pelet Layak', NULL, 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Penggilingan / Pembuatan Pakan & Tepung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makanan Pelet Krustasea', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makanan Pelet Moluska', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makanan Pelet Invertebrata', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Penyu', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Bagian Ikan Yang Tidak Dapat Dimakan', 'Non Edible Fish Offal', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pengolahan Non-Pangan (UPPN)', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Bagian Hewan Non-Pangan', 'Non-Edible Animal Parts', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pengolahan Hasil Sampingan', NULL, 'master_exim_reference'),
('asalbahanbaku', 'asal_bahan_baku', 'Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Cangkang Moluska Krustasea', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Terumbu Karang & Cangkang Moluska', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ambergris Castoreum Musang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Telur Susu Krustasea', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Udang', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Artemia', 'Artemia', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kulit', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Produk Krustasea / Moluska Lainnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Spons Alami', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Tanaman Air', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Tanaman Stek Slip', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Tanaman Air/Hias Hidup', 'Live Aquatic Plants', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Rumput Laut', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_ekspor_utama', 'Rumput Laut', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Eucheuma Spinosum', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Kering-Pangan', 'Dried-Fit for Human Consumption', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Eucheuma Cottonii', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Gracilari spp.', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Rumput Laut Lainnya', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Kering-Non Pangan', 'Dried-Unfit for Human Consumption', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Agar-Agar', 'Agar', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Karagenan', 'Carageenan', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Lemak-Minyak Ikan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hati Fraksinya Fraksi', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Fraksi Padat', 'Solid Fractions', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Fraksi Tidak Padat', 'Not Solid Fractions', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lemak & Minyak Ikan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lemak Fraksinya Dari', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Minyak/Lemak Hewani', 'Animal Fats and Oils', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Ekstraksi & Pemurnian', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lemak Hewani Dioksidasi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Spermaceti Baik Yang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sari', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Ekstrak dan Sari', 'Extracts and Juices', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sari Krustasea Moluska', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Ekstrak Dan Sari Ikan', 'Extracts And Juices Of Fish', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Haring Yang Sudah', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Kaleng-Pouch', 'Canned-Pouch', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Precooked', 'Precooked', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirip Hiu Olahan', NULL, 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pengolahan Hasil Perikanan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Daging Ikan Olahan (Tidak Dicincang)', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sosis', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Sosis Ikan', 'Fish Sausage', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Pelumatan Daging Ikan (Surimi)', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bakso', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Bakso Ikan', 'Fish Meatball', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pasta', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Pasta Ikan', 'Fish Paste', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Olahan Sosis & Bakso Ikan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kaviar', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Kaviar', 'Caviar', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pengganti Kaviar', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Pengganti Kaviar', 'Caviar Substitute', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Matang Beku', 'Frozen Cooked', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Bakso Udang', 'Srimp Meatball', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Breaded', 'Breaded', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Cumi-cumi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sediaan Makanan Yang', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Sediaan Makanan/Bumbu', 'Food Preparations/Seasoning', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pasta Isi Krustasea', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Ragi Tidak Aktif', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Saus', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Saus Ikan', 'Fish Sauce', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Lainnya', 'Others', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Terasi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pelet Pakan Ikan', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Tidak Layak Untuk Konsumsi Manusia', 'Unfit For Human Consumption', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makanan Pelet Dari', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bungkil Residu Padat', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Pakan/Tepung/Bungkil', 'Flours, Meals and Feeds', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Premix Suplemen Pakan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Olahan Dari Jenis', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Garam', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Garam Meja', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Garam & Mineral', 'Salt and Minerals', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Garam Batu Yang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Air Laut', NULL, 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Penyediaan Sarana & Prasarana', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Garam Kandungan Natrium', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Garam Natrium Klorida', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Pasir dan Tanah', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pasir Silika Pasir', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pasir Alam Dari', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lempung Bentonit Lempung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Makanan Fosil Yang', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Mineral', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_impor_utama', 'Bahan Kimia & Aditif Tambak', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hidrogen Peroksida Baik', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Bahan Kimia & Aditif Tambak', 'Chemicals and Aquaculture Inputs', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Formulasi Kimia & Input Budidaya', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bahan Kimia', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Mentol', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sterol Inositol', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Garam-garam Dari Asam', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Imina Turunannya Garamnya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Senyawa Yang Mengandung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Vitamin Turunannya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Vitamin B1 Turunannya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Vitamin B2 Turunannya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Asam D- Dl-pantotenat', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Vitamin B6 Turunannya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Vitamin B12 Turunannya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Vitamin Turunannya Tidak', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Produk Farmasi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kultur Sel Baik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Darah Manusia Darah', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Obat-obatan Yang Mengandung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Antiseptik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Obat Yang Terdiri', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Pupuk', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pupuk Yang Hanya', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pupuk Mineral', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Bahan pewarna', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Bahan Pewarna Yang', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Sarana Produksi & Input', 'Production Equipment and Inputs', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Zat dan Enzim', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Gelatin Turunan Gelatin', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Gelatin & Lem Ikan', 'Gelatin and Fish Glues', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Ekstraksi & Pemurnian Enzim/Gelatin', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Isinglass Tidak Lem', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lem', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Lem Yang Berasal', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Pepton Turunannya Zat', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Herbisida Desinfektan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Desinfektan Mengandung Campuran', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Inisiator Reaksi Pemercepat', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Media Kultur Yang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Biodesel Tidak Mengandung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Biodiesel Tidak Mengandung', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Biodiesel Campurannya Mengandung', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Plastik-Karet', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Asam Alginat Garam', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Plastik/Kemasan Perikanan', 'Fishery Packaging Plastics', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Polimer Alam Polimer', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Plastik Pelampung Untuk', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Jangat Dan Kulit', 'Hides And Skins', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Kayu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kayu Tropis Meranti', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Kayu Pembuatan Kapal', 'Boat Building Wood Materials', 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kayu Tropis Jati', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kayu Kayu Tropis', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kayu Gergajian Hs', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Mutiara', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Mutiara', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Alam', 'Natural', 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Budidaya Air Tawar', 'Cultured In Freshwater', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Perhiasan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perhiasan Imitasi Dari', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Mutiara & Hasil Kerang', 'Pearls and Shell Articles', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Kerajinan Mutiara & Biota Laut', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Mesin-Elektronik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kabel Telepon Bawah', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Peralatan & Sensor Maritim', 'Maritime Gear and Sensors', 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Kapal', NULL, 'master_exim_reference'),
('komoditas', 'prioritas_impor_utama', 'Armada & Alat Tangkap', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kapal Penangkap Tonase', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Armada & Kapal Penangkap', 'Fishing Vessels and Floating Structures', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Galangan & Pembuatan Kapal', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kapal Pabrik Kapal', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Tiup Dilengkapi', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Karet Tidak', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Tiup Berat', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Layar Tiup', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Layar Perahu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Motor Perahu', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Perahu Motor Tiup', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kapal Pesiar Kapal', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Alat Ukur', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Serat Optik & Kabel', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Mainan-Olahraga', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Joran Pancing', NULL, 'master_exim_reference'),
('bentuk', 'bentuk_produk_id', 'Alat Tangkap & Pancing', 'Fishing Tackle and Equipment', 'master_exim_reference'),
('pengolahan', 'jenis_pengolahan', 'Fabrikasi Alat Penangkapan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kail Baik Yang', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Gulungan Pancing', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Alat Pancing Pancing', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Sirkus Keliling Kebun', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Wahana Taman Hiburan', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hiburan Taman Air', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Hiburan Pasar Malam', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Teater Keliling', NULL, 'master_exim_reference'),
('komoditas', 'kelompok_komoditas', 'Barang Pabrik', NULL, 'master_exim_reference'),
('jenis', 'jenis_produk', 'Kapsul Gelatin Untuk', NULL, 'master_exim_reference'),
('komoditas', 'komoditas_1_2017', 'Binatang Melata', 'Reptiles', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Paha Kodok', 'Frog''S Legs', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Ikan Hias', 'Ornamental Fish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Trout', 'Trout', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Sidat', 'Eels', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Ikan Lainnya', 'Other Fish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Ikan Pipih Lainnya', 'Other Flat Fish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Tuna-Tongkol-Cakalang', 'Tunas, Tonggol, Skipjack', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Teri', 'Anchovies', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Makarel', 'Mackerel', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Cobia', 'Cobia', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Todak', 'Swordfish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Tilapia', 'Tilapias', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Catfish', 'Catfish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Karper', 'Carps', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Pari Dan Skates', 'Rays And Skates', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Seabream', 'Seabreams', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Kerapu', 'Groupers', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Layur, Gulama, Reeve''S Croakers, Bigeye Croakers', 'Savalai Hairtails, Belanger''S Croakers, Reeve''S Croakers, Bigeye Croakers', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Scad Torpedo, Spotted Sicklefish, Barracuda Besar', 'Scad Torpedo, Spotted Sicklefish, Great Barracuda', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Bawal', 'Pomfrets', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Kakap Merah', 'Mangrove Red Snappers', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Gabus Dan Nile Perch', 'Snakeheads And Nile Perch', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Halibut', 'Halibut', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Sarden-Sardinella', 'Sardines-Sardinella', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Dogfish Dan Hiu Lainnya', 'Dogfish And Other Sharks', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Seabass', 'Seabass', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Bluntnose Lizardfish', 'Bluntnose Lizardfish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Hati-Telur Ikan', 'Livers And Roes Of Fish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Sirip Hiu', 'Shark Fin', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Bagian Ikan Lainnya', 'Other Fish Offal', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Cod', 'Cod', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Haddock', 'Haddock', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Alaska Pollack', 'Alaska Pollack', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Salmon', 'Salmon', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Lobster', 'Lobsters', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Udang', 'Shrimps', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Tepung Ikan-Pellet-Makanan Ikan', 'Flours, Meals, Pellets', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Olahan Ikan Lainnya', 'Other Prepared Fish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Rajungan-Kepiting', 'Crabs Or Swimming Crabs', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Kekerangan', 'Scallops, Clams, Cockles, Ark Shells, Mussels', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Cumi-Sotong-Gurita', 'Cuttle Fish, Squid, Octopus', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Siput (Selain Siput Laut)', 'Snails (Other Than Sea Snails)', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Abalon', 'Abalone', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Stromboid Conchs', 'Stromboid Conchs', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Moluska Lainnya', 'Other Molluscs', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Teripang', 'Sea Cucumbers', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Bulu Babi', 'Sea Urchins', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Ubur-Ubur', 'Jellyfish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Invertebrata Air Lainnya', 'Other Aquatic Invertebrates', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Rumput Laut', 'Seaweeds', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Lemak-Minyak Ikan', 'Fats And Oils Fish', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_1_2017', 'Mutiara', 'Pearls', 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Binatang Melata', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Paha Kodok', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Ikan Hias', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Salmon-Trout', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Sidat', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Ikan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Kerapu', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Ikan Pipih Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Tuna-Tongkol-Cakalang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Teri', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Makarel', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Cobia', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Todak', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Tilapia', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Catfish', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Karper', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Pari Dan Skates', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Seabream', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Layur, Gulama, Reeve''S Croakers, Bigeye Croakers', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Scad Torpedo, Spotted Sicklefish, Barracuda Besar', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bawal', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Kakap Merah', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Gabus Dan Nile Perch', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Halibut', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Sarden-Sardinella', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Dogfish Dan Hiu Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Seabass', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bluntnose Lizardfish', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bandeng', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Silver grunts', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Hati-Telur Ikan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Sirip Hiu', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bagian Ikan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Cod', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Haddock', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Alaska Pollack', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Lemadang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'surimi', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Lobster', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Rajungan-Kepiting', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Udang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Tepung Ikan-Pellet-Makanan Ikan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Olahan Ikan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Kekerangan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Cumi-Sotong-Gurita', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Moluska Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Teripang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bulu Babi', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Ubur-Ubur', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Invertebrata Air Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Tanaman Air', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Rumput Laut', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Lemak-Minyak Ikan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Garam', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Pasir dan Tanah', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bahan Kimia', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Produk Farmasi', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Pupuk', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Bahan pewarna', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Zat dan Enzim', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Plastik-Karet', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Kayu', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Mutiara', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Perhiasan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Mesin-Elektronik', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Kapal', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Alat Ukur', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Mainan-Olahraga', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_4_2024', 'Barang Pabrik', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Binatang Melata', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Paha Kodok', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Ikan Hias', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Salmon-Trout', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Sidat', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Ikan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Kerapu', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Ikan Pipih Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Tuna-Cakalang-Tongkol', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Teri', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Makarel', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Cobia', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Todak', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Tilapia', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Catfish', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Karper', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Pari Dan Skates', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Seabream', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Layur, Gulama, Reeve''S Croakers, Bigeye Croakers', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Scad Torpedo, Spotted Sicklefish, Barracuda Besar', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bawal', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Kakap Merah', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Gabus Dan Nile Perch', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Halibut', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Sarden-Sardinella', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Dogfish Dan Hiu Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Seabass', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bluntnose Lizardfish', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bandeng', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Silver grunts', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Hati-Telur Ikan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Sirip Hiu', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bagian Ikan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Cod', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Haddock', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Alaska Pollack', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Lemadang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'surimi', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Lobster', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Rajungan-Kepiting', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Udang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Tepung Ikan-Pellet-Makanan Ikan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Olahan Ikan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Kekerangan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Cumi-Sotong-Gurita', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Moluska Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Teripang', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bulu Babi', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Ubur-Ubur', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Invertebrata Air Lainnya', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Tanaman Air', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Rumput Laut', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Lemak-Minyak Ikan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Garam', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Pasir dan Tanah', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bahan Kimia', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Produk Farmasi', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Pupuk', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Bahan pewarna', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Zat dan Enzim', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Plastik-Karet', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Kayu', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Mutiara', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Perhiasan', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Mesin-Elektronik', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Kapal', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Alat Ukur', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Mainan-Olahraga', NULL, 'raw_exim_ekspor_202606'),
('komoditas', 'komoditas_5_2026', 'Barang Pabrik', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Hidup', 'Live', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Segar, Dingin Atau Beku', 'Fresh, Chilled Or Frozen', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Diasinkan Atau Dalam Air Garam, Dikeringkan, Diasapi', 'Salted Or In Brine, Dried, Smoked', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Ikan Hias Air Tawar', 'Freshwater Ornamental Fish', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Ikan Hias Air Laut', 'Marine Ornamental Fish', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Segar Atau Dingin', 'Fresh Or Chilled', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Beku', 'Frozen', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Fillet', 'Fillets', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Daging Lainnya', 'Other Meat', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Diolah-Diawetkan', 'Prepared Or Preserved', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Dikeringkan', 'Dried', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'diasinkan', 'Salted', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Diasinkan', 'Salted', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Bagian Ikan Yang Dapat Dimakan', 'Edible Fish Offal', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Diasapi', 'Smoked', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Layak Untuk Konsumsi Manusia', 'Fit For Human Consumption', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'hidup', 'Live', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Dalam Kemasan Kedap Udara', 'Airtight Containers', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Tidak Dalam Kemasan Kedap Udara', 'Others', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Bagian Ikan Yang Tidak Dapat Dimakan', 'Non Edible Fish Offal', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Tidak Layak Untuk Konsumsi Manusia', 'Unfit For Human Consumption', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Agar-Agar', 'Agar-Agar', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Karagenan', 'Carageenan', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Fraksi Tidak Padat', 'Not Solid Fractions', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Fraksi Padat', 'Solid Fractions', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Ekstrak Dan Sari Ikan', 'Extracts And Juices Of Fish', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Sosis Ikan', 'Fish Sausage', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Bakso Ikan', 'Fish Meatball', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Pasta Ikan', 'Fish Paste', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Bakso Udang', 'Srimp Meatball', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Lainnya', 'Others', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Jangat Dan Kulit', 'Hides And Skins', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_1', 'Budidaya Air Tawar', 'Cultured In Freshwater', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Hidup', 'Live', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Segar, Dingin Atau Beku', 'Fresh, Chilled Or Frozen', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Diasinkan Atau Dalam Air Garam, Dikeringkan, Diasapi', 'Salted Or In Brine, Dried, Smoked', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Ikan Hias Air Tawar', 'Freshwater Ornamental Fish', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Ikan Hias Air Laut', 'Marine Ornamental Fish', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Segar-Dingin', 'Fresh Or Chilled', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Hidup-Segar-Dingin', 'Live-Fresh-Chilled', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Mentah Beku', 'Frozen Raw', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Utuh Beku', 'Frozen Whole', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Fillet', 'Fillets', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Daging Lainnya', 'Other Meat', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Diasapi', 'Smoked', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Dikeringkan', 'Dried', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'diasinkan', 'Salted', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Diasinkan', 'Salted', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Bagian Ikan Yang Dapat Dimakan', 'Edible Fish Offal', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Diasapi Beku', 'Smoked-Frozen', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Layak Untuk Konsumsi Manusia', 'Fit For Human Consumption', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Dalam Kemasan Kedap Udara', 'Airtight Containers', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Olahan Lainnya', 'Others', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Diolah-Diawetkan', 'Prepared-Preserved', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Bagian Ikan Yang Tidak Dapat Dimakan', 'Non Edible Fish Offal', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Kering-Pangan', 'Dried-Fit for Human Consumption', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Kering-Non Pangan', 'Dried-Unfit for Human Consumption', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Agar-Agar', 'Agar', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Karagenan', 'Carageenan', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Fraksi Tidak Padat', 'Not Solid Fractions', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Fraksi Padat', 'Solid Fractions', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Ekstrak Dan Sari Ikan', 'Extracts And Juices Of Fish', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Tidak Dalam Kemasan Kedap Udara', 'Prepared Or Preserved', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Kaleng-Pouch', 'Canned-Pouch', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Precooked', 'Precooked', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Sosis Ikan', 'Fish Sausage', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Bakso Ikan', 'Fish Meatball', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Pasta Ikan', 'Fish Paste', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Matang Beku', 'Frozen Cooked', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Bakso Udang', 'Srimp Meatball', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Breaded', 'Breaded', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Lainnya', 'Others', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Tidak Layak Untuk Konsumsi Manusia', 'Unfit For Human Consumption', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Jangat Dan Kulit', 'Hides And Skins', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_3_2026', 'Budidaya Air Tawar', 'Cultured In Freshwater', 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Segar-Dingin', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Mentah Beku', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Diasinkan', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Hidup', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Dikeringkan', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Diolah-Diawetkan', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Layak Untuk Konsumsi Manusia', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Daging Lainnya', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Tidak Layak Untuk Konsumsi Manusia', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Diasapi', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Utuh Beku', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Tidak Dalam Kemasan Kedap Udara', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Dalam Kemasan Kedap Udara', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Fillet', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Olahan Lainnya', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Matang Beku', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Kering-Pangan', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Hidup-Segar-Dingin', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Kering-Non Pangan', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Agar-Agar', NULL, 'raw_exim_ekspor_202606'),
('bentuk', 'bentuk_5_2026', 'Karagenan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Ikan Koi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Ikan Mas', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Cupang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Arwana', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Ikan Kerapu Karang Macan Tutul', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Ikan Kerapu Belimbing', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Ikan Kerapu Bungkuk', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Tuna Sirip Kuning', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Tuna Mata Besar', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Tuna Sirip Biru Selatan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Tuna', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Tuna Albacore', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Cakalang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Tuna Ekor Panjang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Mud Crab', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Rajungan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Snow Crab', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Udang Lainnya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Udang Windu', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Udang Vannamei', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Udang Galah', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Eucheuma Spinosum', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Eucheuma Cottonii', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Gracilari spp', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis', 'Olahan Udang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Reptil', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Hewan Subpos 010611', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Katak', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Ikan Hias Air Tawar', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Koi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Ikan Mas', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Cupang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Arwana', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Ikan Hias', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Trout', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Belut', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kerapu', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pipih Halibut Plaice', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Sirip Kuning', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Mata Besar', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Sirip Biru Selatan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Lainnya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Teri', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Makarel', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kobia', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Ikan Pedang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bonito / Makarel / Sarden', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tilapia', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Patin', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sepat', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kakap', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Layur', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Torpedo Scads Sabit', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bawal Hitam', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kakap Merah', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Laut Kode Hs', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lele', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Gabus', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Halibut', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Albakora', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Cakalang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Ekor Panjang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sarden / Lemuru', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bawal', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Dari Famili Bregmacerotidae', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Dogfish Hiu', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pari Pari', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kadal Berhidung Tumpul', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bandeng', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Geram Perak', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Hati Telur Sisik', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sirip Hiu', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kepala Ekor Isi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Fillet Ikan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Dari Dari Subpos', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Alaska Pollack', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Salmon', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tuna Olahan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lemadang / Mahi-mahi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Yang Dibekukan Dari', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Surimi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Dari Kode Hs', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Hati Telur Air', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bonito / Sarden', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Jeroan Yang Dapat', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tetapi Tidak Air', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Asin Tetapi Tidak', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Direndam Air Garam', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sirip Yang Air', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lobster', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kepiting Bakau', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kepiting Lainnya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Rajungan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kepiting Subtropis', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Udang Subtropis', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Udang Windu', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Udang Vaname', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Udang Lainnya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Krustasea Yang Tidak', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Udang Galah', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Krustasea Tidak Diklasifikasikan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kepiting Olahan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kerang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Cumi-Sotong', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Gurita', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Siput Siput Laut', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Abalon', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Keong Stromboid', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Moluska Baik Cangkang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bulu Babi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Ubur-ubur', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Invertebrata Air Krustasea', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Makanan Pelet Layak', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Makanan Pelet Krustasea', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Cangkang Moluska Krustasea', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Terumbu Karang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Telur Susu Krustasea', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kulit', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Krustasea Moluska Invertebrata', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tanaman Stek Slip', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Eucheuma Spinosum', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Eucheuma Cottonii', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Gracilari spp.', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Rumput Laut Lainnya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Hati Fraksinya Fraksi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lemak Serta Fraksinya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lemak Fraksinya Dari', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sari', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sari Krustasea Moluska', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sirip Hiu Yang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Tetapi Tidak Dicincang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sosis', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bakso', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pasta', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Yang Sosis Bakso', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Cumi-cumi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Sediaan Makanan Yang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Ragi Tidak Aktif', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Udang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Terasi', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Makanan Pelet Kandungan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Makanan Pelet Dari', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Premix Suplemen Pakan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Olahan Dari Jenis', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Garam Meja', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Air Laut', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Garam Natrium Klorida', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pasir Silika Pasir', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lempung Bentonit Lempung', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Mentol', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Imina Turunannya Garamnya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Vitamin Turunannya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Asam D- Dl-pantotenat', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Vitamin B12 Turunannya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Vitamin Turunannya Tidak', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kultur Sel Baik', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Darah Manusia Darah', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Obat-obatan Yang Mengandung', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Antiseptik', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Obat Yang Terdiri', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pupuk Yang Hanya', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pupuk Mineral', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Bahan Pewarna Yang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Lem Yang Berasal', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Pepton Turunannya Zat', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Herbisida Desinfektan', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Desinfektan Mengandung Campuran', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Inisiator Reaksi Pemercepat', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Polimer Alam Polimer', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Plastik Pelampung Untuk', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kayu Tropis Meranti', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kayu Gergajian Hs', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Mutiara', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Perhiasan Imitasi Dari', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kabel Telepon Bawah', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Perahu Tiup Berat', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kapal Pesiar Kapal', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Serat Optik Bundel', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Joran Pancing', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Kail Baik Yang', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Gulungan Pancing', NULL, 'raw_exim_ekspor_202606'),
('jenis', 'jenis_2_2026', 'Alat Pancing Pancing', NULL, 'raw_exim_ekspor_202606');
